name: Lint-and-Test

on:
  push:
    branches: [main]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: List directory
      run: ls -l
    - uses: actions/checkout@v3
    - name: List directory
      run: ls -l
    - name: SetUp Python3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Make tests
      run: pytest
        

  
